language: node_js
node_js:
  - "10"
script:
  - npm install iconoteka/iconoteka#master
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: build
  on:
    branch: develop
